name: hasseldine
favicon: null
layout_spectrum: 0.99368
typography_spectrum: 0.24097
title: 'personal and professional musings on humanity, education, science and technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6dfe6'
    - '#040404'
    - '#d4b26a'
    - '#644017'
    - '#97692a'
  brandStrength: 0.5
  lightness: 0.7739099517930299
  saturation: 0.5625
  rhythmicContrast: 0.63778305798769
purpose: []
